Implementing follow feature on profile page
projectIncubator/pi-frontend pull request #32
Opened 2020-08-04 00:13 UTC by 14yapkc1

2020-08-08 00:06 UTC, hal-shin requested changes
There's a bug with spamming the follow button--this should be fixed up now, rather than later.

Otherwise, looking good!

2020-08-08 00:06 UTC, hal-shin commented on src/components/UserInfo.jsx
> +import React, { useState, useEffect } from 'react';
useEffect is no longer used--it should be removed

2020-08-08 00:06 UTC, hal-shin commented on src/components/UserInfo.jsx
> +      user.following.map((u) => u.id === id).includes(true)
Interesting...

2020-08-08 00:06 UTC, hal-shin commented on src/components/UserInfo.jsx
> +  const unfollowUser = async () => {
I generally tend do organize React code so that logic is on the top and visual components are on the bottom. It helps to find the thing you're looking for that way. Could we move this up so that it's above the `avatarSection` and `identitiySection`?

2020-08-08 00:06 UTC, communitybicycle commented on src/components/UserInfo.jsx
> +  };
There's a bug--I spammed the follow button and it created an odd error. I'm now following the profile, but the button still says "Follow" and the follow count has gone up +1, and I can't unfollow.

2020-08-08 00:06 UTC, communitybicycle commented on src/contexts/AuthProvider.js
> +      } catch (err) {}
Not sure if this is best practice... is there a reason you didn't make the scope of the try/catch on the entire function?

2020-08-08 00:06 UTC, communitybicycle commented on src/contexts/AuthProvider.js
> +        user: user,
I believe `user` is the same as `user: user` in this instance

2020-08-08 00:06 UTC, communitybicycle commented on src/pages/Profile.jsx
> +const Profile = ({ classes }) => {
LOL I see you like `const` functions more

2020-08-08 00:08 UTC, communitybicycle commented on src/components/UserInfo.jsx
> +      user.following.map((u) => u.id === id).includes(true)
Although it still works, just be mindful that if `user` doesn't exist, the state will default to `undefined`, I think, instead of a `false`

2021-06-04 18:29 UTC, communitybicycle commented
Any idea why the changes are shown as complete removals and complete additions? Makes tracking the actual changes difficult...

2021-06-04 19:44 UTC, 14yapkc1 commented
> Any idea why the changes are shown as complete removals and complete additions? Makes tracking the actual changes difficult...

I am not sure, Rey said that it might be because of the spacing issues :( I'll try run prettier and see if it fixes anything

2021-06-04 20:03 UTC, 14yapkc1 commented
yeah it's broken after I ran prettier so I have no idea

2021-06-04 20:03 UTC, communitybicycle commented
> > Any idea why the changes are shown as complete removals and complete additions? Makes tracking the actual changes difficult...
> 
> I am not sure, Rey said that it might be because of the spacing issues :( I'll try run prettier and see if it fixes anything

It must be an end of line issue. Odd... but since you've specified the end of line format in prettierrc, it should be good going forward

2021-06-10 16:44 UTC, communitybicycle approved these changes, later dismissed
Welp, this is tricky to review. We'll just merge it for now and resolve any issues going forward...

2021-06-22 01:08 UTC, merged